services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - VERSION=docker
    volumes:
      - ${BASE_FOLDER}/config/plex:/config
      - ${BASE_FOLDER}/data:/data
    restart: unless-stopped

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - NZBGET_USER=${NZBGET_USER}
      - NZBGET_PASS=${NZBGET_PASS}
    volumes:
      - ${BASE_FOLDER}/config/nzbget:/config
      - ${BASE_FOLDER}/data:/data
    ports:
      - 6789:6789
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - ${BASE_FOLDER}/config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - ${BASE_FOLDER}/config/sonarr:/config
      - ${BASE_FOLDER}/data:/data
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - ${BASE_FOLDER}/config/radarr:/config
      - ${BASE_FOLDER}/data:/data
    ports:
      - "7878:7878"
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - ${BASE_FOLDER}/config/lidarr:/config
      - ${BASE_FOLDER}/data:/data
    ports:
      - "8686:8686"
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - ${BASE_FOLDER}/config/readarr:/config
      - ${BASE_FOLDER}/data:/data
    ports:
      - "8787:8787"
    restart: unless-stopped

  listenarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: listenarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - ${BASE_FOLDER}/config/listenarr:/config
      - ${BASE_FOLDER}/data:/data
    ports:
      - "8788:8787"
    restart: unless-stopped

  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    container_name: pinchflat
    environment:
      - TZ=America/New_York
    ports:
      - "8945:8945"
    volumes:
      - ${BASE_FOLDER}/config/pinchflat:/config
      - ${BASE_FOLDER}/data/media/youtube:/downloads
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr
    container_name: overseerr
    environment:
      - TZ=Pacific/Auckland
    volumes:
      - ${BASE_FOLDER}/config/overseerr:/app/config
    ports:
      - "5055:5055"
    restart: unless-stopped